### PR TITLE
1 10 stable

### PR DESCRIPTION
**Pull request by chandra381**
is LiveQuery is depricated in JQuery 1.10.2 version.. because i am receiving .livequery is not a function error after upgrading my application from Jquery 1.9 to 1.10.2 version.

### CODE REVIEW

**Comment by scottgonzalez** [comment]
I don't know what you're trying to accomplish, but this has nothing to do with jQuery UI.
